In [11]:
import tensorflow as tf
import numpy as np

In [12]:
tf.constant([True,False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [13]:
tf.constant(1)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [14]:
tf.constant('hello')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [15]:
tf.constant(2,dtype=tf.double)

<tf.Tensor: shape=(), dtype=float64, numpy=2.0>

In [17]:
tf.convert_to_tensor(np.ones([3,3]))

<tf.Tensor: shape=(3, 3), dtype=float64, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])>

In [18]:
tf.random.uniform([3,3],minval=0,maxval=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.80004394, 0.691013  , 0.25838208],
       [0.82356966, 0.3558935 , 0.8508774 ],
       [0.92346835, 0.9149966 , 0.9915956 ]], dtype=float32)>

In [20]:
idx = tf.range(10)
print(idx)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [22]:
idx = tf.random.shuffle(idx)
print(idx)

tf.Tensor([0 5 3 6 1 7 8 9 4 2], shape=(10,), dtype=int32)


In [28]:
x = tf.ones([1,5,5,3])
print(x)

tf.Tensor(
[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]], shape=(1, 5, 5, 3), dtype=float32)
